# Generated by Django 4.1.13 on 2023-12-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_shiekh_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiekh',
            name='image',
            field=models.ImageField(default='2:23', upload_to='images/'),
            preserve_default=False,
        ),
    ]
