# Generated by Django 4.1.13 on 2023-12-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0003_alter_shiekh_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='2:30'),
            preserve_default=False,
        ),
    ]
