# Generated by Django 4.1.13 on 2023-12-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0004_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioepisode',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default='2012-12-12'),
            preserve_default=False,
        ),
    ]
