# Generated by Django 4.2.8 on 2023-12-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0007_audioepisode_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiekh',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
