# Generated by Django 4.2.8 on 2023-12-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0008_alter_shiekh_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiekh',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
