# Generated by Django 4.2.8 on 2023-12-24 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0010_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='logo',
            new_name='image',
        ),
    ]
