# Generated by Django 4.2.8 on 2023-12-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0011_rename_logo_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='bukMosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='buk_mosque_logo')),
            ],
        ),
    ]
