# Generated by Django 4.2.8 on 2023-12-24 14:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0012_bukmosque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioepisode',
            name='title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
        migrations.AlterField(
            model_name='audioepisode',
            name='audio_file',
            field=models.FileField(upload_to='audios'),
        ),
        migrations.AlterField(
            model_name='bukmosque',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shiekh',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
