# Generated by Django 4.2.8 on 2023-12-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0013_remove_audioepisode_title_remove_book_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioepisode',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
