# Generated by Django 4.2.8 on 2023-12-24 14:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0014_audioepisode_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioepisode',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
